### PR TITLE
Updating yarn-monorepo test sample repository.

### PR DESCRIPTION
**Pull request by thavaahariharangit**
[Removed the reference to the non-existing registry repo](https://github.com/dsp-testing/dependabot-core-smoke-yarn-monorepo/commit/d864e3910a2a5a237efa2733ec287db2ef4a8344) and created new sample repo for smoke test.

### CODE REVIEW

**Comment by abdulapopoola** [comment]
Can we use an internal repository to ensure we don't have to consistently update tests?

**Review by abdulapopoola — APPROVED** [review]
Non-blocking comment,

**Comment by thavaahariharangit** [comment]
> Removed the reference to the non-existing registry repo

image
I am unable update the visibility as it is forked.

**Comment by thavaahariharangit** [comment]
> Can we use an internal repository to ensure we don't have to consistently update tests?

image
I am unable to update the visibility as it is forked from the previous.

But I can recreate it. and make it internal

**Pull request merged**
