### PR TITLE
grouped multi-directory smoke tests

### PR DESCRIPTION
**Pull request by jakecoffman**
This won't work until the Core feature is merged: https://github.com/dependabot/dependabot-core/pull/8309

For now it's useful during development to run from the Core directory (assuming the smoke-tests directory is a sibling):

```console
script/dependabot test -f ../smoke-tests/tests/smoke-pip-group-multidir.yaml
```

```console
script/dependabot test -f ../smoke-tests/tests/smoke-npm-group-multidir.yaml
```

```console
script/dependabot test -f ../smoke-tests/tests/smoke-bundler-group-multidir.yaml
```

### CODE REVIEW

**Comment by jakecoffman** [comment]
Since we're targeting security updates first, we may need to add the following properties to the job:
- dependencies
- security-advisories
- security-updates-only: true

**Review by honeyankit — APPROVED** [review]

**Comment by vegeta321311** [comment]
3.2.13.1.1
GEM
  remote: https://rubygems.org/
  specs: 0x331a94dac38795536d418a18cbaaf315d3188684
    mini_portile2 (2.5.3)
    nokogiri (1.11.0)
      mini_portile2 (~> 2.5.0)
      racc (~> 1.4)
    racc (1.7.2)
    rack (3.0.0)

PLATFORMS
  coinbase

DEPENDENCIES
  nokogiri (= 1.11)
  rack (= 3.0.0)

BUNDLED WITH
   2.4.18

**Review by vegeta321311 — APPROVED** [review]
0x2E7Df6483C7E1D2EE6Cb11aC70d37FB060cF6e23

**Comment by vegeta321311** [comment]
__

**Pull request merged**
