### PR TITLE
Upgrade Bundler smoke tests for Ruby 3.3.6

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Ruby 3.3.6 has json 2.7.2 as a default gem. See https://stdgems.org/json/.

This means that when upgrading Dependabot to use Ruby 3.3.6, even if smoke tests cache all network requests to keep the expected lockfile consistent, json will still resolve to 2.7.2 because even if the API only provides older (cached) versions, locally 2.7.2 is still available.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
mmm the vendoring test is not going to work because the `json-2.7.2.gem` file won't be available. Easiest way is probably to regenerate cache and upgrade test expectations.

**Comment by JamieMagee** [comment]
@deivid-rodriguez what's the order in which this PR, cache update, and https://github.com/dependabot/dependabot-core/pull/10250 need to be done?

**Review by JamieMagee — APPROVED** [review]

**Comment by deivid-rodriguez** [comment]
I regenerated the tests to the expectations without cache. So if cache is updated now for those three tests, and I that should make this PR and https://github.com/dependabot/dependabot-core/pull/10250 pass.

**Comment by JamieMagee** [comment]
This PR is still failing, and I can't regenerate the cache for this branch because it's from a fork. Trying to update the `main` branch cache fails too https://github.com/dependabot/smoke-tests/actions/runs/12399106351

**Comment by deivid-rodriguez** [comment]
I see! That failure when generating `smoke-bundler.yaml` cache shows the same diff this PR is proposing so that suggests the PR content is correct.

Possible approaches:

* Recreate this PR from a branch inside the repo and regenerate cache for the three tests updated here from it. Then an alternative PR from that branch should get green.
* Merge this PR with red status and then regenerate cache from main.

**Comment by JamieMagee** [comment]
I copied your branch into this repository and re-ran the cache: https://github.com/dependabot/smoke-tests/actions/runs/12402948853

I restarted the failing workflows for this PR, and one passed, but two still fail.

**Comment by deivid-rodriguez** [comment]
Thank you @JamieMagee! Did you run the cache-one workflow targeting those other two tests?

**Comment by JamieMagee** [comment]
Ah, I thought it was per ecosystem, not per smoke test. I'll re-run now with the remaining failing smoke tests.

**Pull request merged**
