### PR TITLE
Update Yarn Berry smoke test

### PR DESCRIPTION
**Pull request by jeffwidman**
Update the smoke test to reflect the new behavior from: https://github.com/dependabot/dependabot-core/pull/6587

Updated the smoke test by finding the image name from: 
https://github.com/dependabot/dependabot-core/actions/runs/4088153275/attempts/1#summary-11100784166

And then running:
```shell
dependabot --updater-image ghcr.io/dependabot/dependabot-updater-npm:8debf86aa7f584b767a21bf5c477d83b3464870a test -f tests/smoke-yarn-berry.yaml -o tests/smoke-yarn-berry.yaml
```

### CODE REVIEW

**Comment by jeffwidman** [comment]
Marking as draft as I want to inspect the diff--I don't understand the triggering PR well enough to know if the smoke test needs updating, or the original PR...

**Comment by jeffwidman** [comment]
Relevant diff:
```diff
diff --git a/tests/smoke-yarn-berry.yaml b/tests/smoke-yarn-berry.yaml
index 5dfa216..451d08a 100644
--- a/tests/smoke-yarn-berry.yaml
+++ b/tests/smoke-yarn-berry.yaml
@@ -65,9 +65,18 @@ output:
                 - name: '@ampproject/remapping'
                   requirements: []
                   version: 2.2.0
+                - name: '@babel/code-frame'
+                  requirements: []
+                  version: 7.18.6
                 - name: '@babel/compat-data'
                   requirements: []
                   version: 7.20.1
+                - name: '@babel/core'
+                  requirements: []
+                  version: 7.20.2
+                - name: '@babel/generator'
+                  requirements: []
+                  version: 7.20.4
                 - name: '@babel/helper-compilation-targets'
                   requirements: []
                   version: 7.20.0
@@ -86,6 +95,9 @@ output:
                 - name: '@babel/helper-module-transforms'
                   requirements: []
                   version: 7.20.2
+                - name: '@babel/helper-plugin-utils'
+                  requirements: []
+                  version: 7.20.2
                 - name: '@babel/helper-simple-access'
                   requirements: []
                   version: 7.20.2
@@ -95,6 +107,9 @@ output:
                 - name: '@babel/helper-string-parser'
                   requirements: []
                   version: 7.19.4
+                - name: '@babel/helper-validator-identifier'
+                  requirements: []
+                  version: 7.19.1
                 - name: '@babel/helper-validator-option'
                   requirements: []
                   version: 7.18.6
@@ -104,6 +119,9 @@ output:
                 - name: '@babel/highlight'
                   requirements: []
                   version: 7.18.6
+                - name: '@babel/parser'
+                  requirements: []
+                  version: 7.20.3
                 - name: '@babel/plugin-syntax-async-generators'
                   requirements: []
                   version: 7.8.4
@@ -143,6 +161,15 @@ output:
                 - name: '@babel/plugin-syntax-typescript'
                   requirements: []
                   version: 7.20.0
+                - name: '@babel/template'
+                  requirements: []
+                  version: 7.18.10
+                - name: '@babel/traverse'
+                  requirements: []
+                  version: 7.20.1
+                - name: '@babel/types'
+                  requirements: []
+                  version: 7.20.2
                 - name: '@bcoe/v8-coverage'
                   requirements: []
                   version: 0.2.3
@@ -203,6 +230,15 @@ output:
                 - name: '@jridgewell/resolve-uri'
                   requirements: []
                   version: 3.1.0
+                - name: '@jridgewell/set-array'
+                  requirements: []
+                  version: 1.1.2
+                - name: '@jridgewell/sourcemap-codec'
+                  requirements: []
+                  version: 1.4.14
+                - name: '@jridgewell/trace-mapping'
+                  requirements: []
+                  version: 0.3.17
                 - name: '@npmcli/fs'
                   requirements: []
                   version: 2.1.2
@@ -230,9 +266,15 @@ output:
                 - name: '@types/babel__template'
                   requirements: []
                   version: 7.4.1
+                - name: '@types/babel__traverse'
+                  requirements: []
+                  version: 7.18.2
                 - name: '@types/graceful-fs'
                   requirements: []
                   version: 4.1.5
+                - name: '@types/istanbul-lib-coverage'
+                  requirements: []
+                  version: 2.0.4
                 - name: '@types/istanbul-lib-report'
                   requirements: []
                   version: 3.0.0
@@ -3426,9 +3468,9 @@ output:
                       linkType: hard
 
                     "jquery@npm:^3.6.1":
-                      version: 3.6.1
-                      resolution: "jquery@npm:3.6.1"
-                      checksum: 6177d866a74f1137cad800f142c7cdbd5ab19cd4282546f8bdb4890c9f933b1d542ab96f2aa15d007e43c98de7315b0513e849ec5359d3ac5640f720892fe547
+                      version: 3.6.3
+                      resolution: "jquery@npm:3.6.3"
+                      checksum: 0fd366bdcaa0c84a7a8751ce20f8192290141913978b5059574426d9b01f4365daa675f95aab3eec94fd794d27b08d32078a2236bef404b8ba78073009988ce6
                       languageName: node
                       linkType: hard
 
@@ -4638,7 +4680,7 @@ output:
                               "packageLocation": "./",\
                               "packageDependencies": [\
                                 ["jest", "virtual:8985bfe6ba677cda0766851544d123cd66efc4326d803dd08493411985e1db9c85edd1c7fb51a4ae1887d7d47a1f703440aea94071abef14051e5ccdcf33d172#npm:28.1.3"],\
-                                ["jquery", "npm:3.6.1"],\
+                                ["jquery", "npm:3.6.3"],\
                                 ["ts-jest", "virtual:8985bfe6ba677cda0766851544d123cd66efc4326d803dd08493411985e1db9c85edd1c7fb51a4ae1887d7d47a1f703440aea94071abef14051e5ccdcf33d172#npm:28.0.8"],\
                                 ["typescript", "patch:typescript@npm%3A4.9.3#~builtin<compat/typescript>::version=4.9.3&hash=d73830"]\
                               ],\
@@ -7754,10 +7796,10 @@ output:
                             }]\
                           ]],\
                           ["jquery", [\
-                            ["npm:3.6.1", {\
-                              "packageLocation": "./.yarn/cache/jquery-npm-3.6.1-6f29087f48-6177d866a7.zip/node_modules/jquery/",\
+                            ["npm:3.6.3", {\
+                              "packageLocation": "./.yarn/cache/jquery-npm-3.6.3-cbc34d2330-0fd366bdca.zip/node_modules/jquery/",\
                               "packageDependencies": [\
-                                ["jquery", "npm:3.6.1"]\
+                                ["jquery", "npm:3.6.3"]\
                               ],\
                               "linkType": "HARD"\
                             }]\
@@ -9074,7 +9116,7 @@ output:
                               "packageDependencies": [\
                                 ["yarn", "workspace:."],\
                                 ["jest", "virtual:8985bfe6ba677cda0766851544d123cd66efc4326d803dd08493411985e1db9c85edd1c7fb51a4ae1887d7d47a1f703440aea94071abef14051e5ccdcf33d172#npm:28.1.3"],\
-                                ["jquery", "npm:3.6.1"],\
+                                ["jquery", "npm:3.6.3"],\
                                 ["ts-jest", "virtual:8985bfe6ba677cda0766851544d123cd66efc4326d803dd08493411985e1db9c85edd1c7fb51a4ae1887d7d47a1f703440aea94071abef14051e5ccdcf33d172#npm:28.0.8"],\
                                 ["typescript", "patch:typescript@npm%3A4.9.3#~builtin<compat/typescript>::version=4.9.3&hash=d73830"]\
                               ],\
```


The rest is just binary diff that can be ignored.

**Comment by jakecoffman** [comment]
If this is failing due to cache, we can merge it with approval. The smoke tests are not required check for this reason!

**Review by jakecoffman — APPROVED** [review]

**Comment by jeffwidman** [comment]
This may be failing due to an actual bug, not fully clear yet:
* https://github.com/dependabot/dependabot-core/issues/6608

**Comment by deivid-rodriguez** [comment]
@jakecoffman Can you advice how to get out of this chicken-and-egg issue? We need the updated for this to pass, and we need this to pass to update the cache. One idea I had at #30 was to temporarily remove the requirement of a green test run to be able to update the cache, and then manually run that modified workflow against this PR to get the cache updated.

**Comment by jakecoffman** [comment]
I kicked off a run pointed at this branch: https://github.com/dependabot/smoke-tests/actions/runs/4109312194

**Comment by jeffwidman** [comment]
I just re-ran the command mentioned in the PR description, to doublecheck and the diff didn't change.

**Comment by deivid-rodriguez** [comment]
@jakecoffman Thanks! I thought I had actually tried running the workflow with this branch as the target `git-ref` and that didn't work. So I thought merging wouldn't fix things either. But I was doing something wrong for sure, since doing it seems to have fixed things 🎉. Thanks again for your help!

So we can merge this right, @jeffwidman?

**Comment by jeffwidman** [comment]
Isn't the concern that merging this codifies the bug described in https://github.com/dependabot/dependabot-core/issues/6608?

I mean, yes, we could do this to make the specs green, but arguably this is a _wrong_ output from the smoke test, it shouldn't be bumping `jquery` past `3.6.1`...

If it's going ot take a while to fix, then yes, we should merge this to ensure no other unexpected regressions as others keep working on `core`, otherwise I'd actually close this w/o merging and fix `core`... I expect we'll still need a small smoke fix here due to https://github.com/dependabot/dependabot-core/pull/6587 now parsing multiple items, but it shouldn't result in the `jquery` bump too...

**Comment by deivid-rodriguez** [comment]
Oh, right! I thought I had amended the spec too. We need to bump the ignore condition to "> 3.6.3" so that the update is actually expected. I don't plan to work on the reported bug for now.

**Comment by deivid-rodriguez** [comment]
I tried to amend the test so that we check something actually expected and not the result of a bug. Not sure if this will pass... 😬

**Comment by deivid-rodriguez** [comment]
It worked! How does it look now @jeffwidman?

**Pull request merged**
