### PR TITLE
Remove empty release notes from smoke tests

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
This is a companion to https://github.com/dependabot/dependabot-core/pull/7118.

I edited these files manually, hopefully I didn't miss anything!

### CODE REVIEW

**Review by jeffwidman — APPROVED** [review]
> I edited these files manually, hopefully I didn't miss anything!

CI will tell us soon enough 😄

**Comment by jakecoffman** [comment]
@deivid-rodriguez some misses? https://github.com/dependabot/smoke-tests/actions/runs/4885355733

**Comment by deivid-rodriguez** [comment]
Could this be a race condition where the scheduled run happened after all images with the core change had been published except for the python ones?

**Comment by jakecoffman** [comment]
Ah, yep looks good: https://github.com/dependabot/smoke-tests/actions/runs/4885682355

Sorry for bugging you, I should have run it again first before asking.

**Comment by deivid-rodriguez** [comment]
No worries!

**Pull request merged**
