### PR TITLE
This is to fix the smoke test failure caused by minor patch update filter functionality.

### PR DESCRIPTION
**Pull request by thavaahariharangit**
This is to fix the smoke test failure due to https://github.com/dependabot/dependabot-core/pull/9967 PR updates.

### CODE REVIEW

**Comment by jakecoffman** [comment]
According to the diff, this test used to create two PRs with titles:
- Bump the phpstan group in /composer with 2 updates
- Bump phpmailer/phpmailer from 5.2.2 to 6.8.0 in /composer

But now it no longer creates any PRs. That seems unexpected?

**Comment by thavaahariharangit** [comment]
> According to the diff, this test used to create two PRs with titles:
> 
> * Bump the phpstan group in /composer with 2 updates
> * Bump phpmailer/phpmailer from 5.2.2 to 6.8.0 in /composer
> 
> But now it no longer creates any PRs. That seems unexpected?

Current implementation always trying to upgrade to latest available/allowable version, If it's not compatible with given composer.json then it will not generate a PR

For example: phpmailer latest version is 6.9.1 as per https://github.com/PHPMailer/PHPMailer/releases

**Comment by jakecoffman** [comment]
I don't know much about how the composer ecosystem works, so I don't want to take the time to load up all that context. If you feel it's valid that the manifests in this smoke tests should not be updated by Dependabot that's ok with me.

However, a smoke test that produces no PRs is not valuable. If this is expected behavior, please update the manifests so that it creates PRs again.

**Comment by jakecoffman** [comment]
Closing since change was reverted and smoke tests are passing now.

**Pull request closed without merging**
