### PR TITLE
Add a smoke test for a grouped bundler PR

### PR DESCRIPTION
**Pull request by brrygrdn**
This PR adds a regression test for the feature/experiment introduced in https://github.com/dependabot/dependabot-core/pull/6884

Before this can merge, #46 needs to be merged as I used it as the base sha for this test and https://github.com/dependabot/dependabot-core/pull/6884 needs to merge in core so this test can be expected to pass when used against the core repo.

### CODE REVIEW

**Comment by jakecoffman** [comment]
Exciting! It would be good to hook this up in workflows as well. You can look at this PR for reference: https://github.com/dependabot/smoke-tests/pull/45

**Comment by brrygrdn** [comment]
@jakecoffman Done, thanks for the head's up!

**Review by jakecoffman — APPROVED** [review]
Looks like you need to regenerate the test again, some of the metadata has changed. Then we can merge it and run the Cache One workflow to get the calls cached!

**Comment by brrygrdn** [comment]
Ah, there's a randomisation issue I think, we just discussed removing the random order for grouped update so I'll do that and fix it.

**Comment by brrygrdn** [comment]
Ah, it was not the randomisation at all - the PR body is stable, you were right some metadata had changed, but I also added the `grouped_update: true` parameter to the API call and didn't update it.

Will merge and cache now.

**Pull request merged**
